### ISSUE TITLE
Remove mention of libgraphqlparser

### ISSUE THREAD

**Issue by relwell** [thebadmonkeydev/graphql_workshop#1]
It looks like rmosolgo doesn't support it anymore: https://github.com/rmosolgo/graphql-ruby/issues/2398

This problem isn't broadly documented, since closed issues can be hard to find.

**Comment by thebadmonkeydev** [comment]
Thanks for pointing this out @relwell 

That's unfortunate :( It would seem to me that this is exactly the place one would want a C module, similar to the C modules underlying string parsing libs.  Something as fundamental as the need to parse a query is a good spot for optimization.  I obviously missed the boat on that one.  I'll remove the mention of it here and also do a bit more research.

Thanks!
